# 워크플로우의 이름을 지정
name: Deploy to Ec2 With Jar

# push 이벤트 지정
# main 브랜치에 push 될 때마다 워크플로우가 실행되도록 지정
on:
  push:
      branches:
        - master

jobs:
# 작업의 이름 지정
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build Docker Image
      working-directory: ./order-system
      run: docker build -t blisle/order_backend:v2 .

    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to DockerHub
      run: docker push -t blisle/order_backend:v2 .